name = "condo-manager-ai"
pages_build_output_dir = "dist"

[vars]
VITE_GROQ_MODEL = "openai/gpt-oss-120b"
VITE_GROQ_API_KEY = "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"
VITE_SUPABASE_URL = "https://qzelgoakigcjvhpxhqha.supabase.co"
VITE_SUPABASE_ANON_KEY = "sb_publishable_8DOf3EoIKBNNZLFOHV2pOQ_MXxmpMG3"
